/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PoliticasRouteImport } from './routes/politicas'
import { Route as NosotrosRouteImport } from './routes/nosotros'
import { Route as CotizacionesRouteImport } from './routes/cotizaciones'
import { Route as ContactoRouteImport } from './routes/contacto'
import { Route as ColeccionesRouteImport } from './routes/colecciones'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TiendaIndexRouteImport } from './routes/tienda/index'
import { Route as TiendaSlugRouteImport } from './routes/tienda/$slug'

const PoliticasRoute = PoliticasRouteImport.update({
  id: '/politicas',
  path: '/politicas',
  getParentRoute: () => rootRouteImport,
} as any)
const NosotrosRoute = NosotrosRouteImport.update({
  id: '/nosotros',
  path: '/nosotros',
  getParentRoute: () => rootRouteImport,
} as any)
const CotizacionesRoute = CotizacionesRouteImport.update({
  id: '/cotizaciones',
  path: '/cotizaciones',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactoRoute = ContactoRouteImport.update({
  id: '/contacto',
  path: '/contacto',
  getParentRoute: () => rootRouteImport,
} as any)
const ColeccionesRoute = ColeccionesRouteImport.update({
  id: '/colecciones',
  path: '/colecciones',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TiendaIndexRoute = TiendaIndexRouteImport.update({
  id: '/tienda/',
  path: '/tienda/',
  getParentRoute: () => rootRouteImport,
} as any)
const TiendaSlugRoute = TiendaSlugRouteImport.update({
  id: '/tienda/$slug',
  path: '/tienda/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/colecciones': typeof ColeccionesRoute
  '/contacto': typeof ContactoRoute
  '/cotizaciones': typeof CotizacionesRoute
  '/nosotros': typeof NosotrosRoute
  '/politicas': typeof PoliticasRoute
  '/tienda/$slug': typeof TiendaSlugRoute
  '/tienda/': typeof TiendaIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/colecciones': typeof ColeccionesRoute
  '/contacto': typeof ContactoRoute
  '/cotizaciones': typeof CotizacionesRoute
  '/nosotros': typeof NosotrosRoute
  '/politicas': typeof PoliticasRoute
  '/tienda/$slug': typeof TiendaSlugRoute
  '/tienda': typeof TiendaIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/colecciones': typeof ColeccionesRoute
  '/contacto': typeof ContactoRoute
  '/cotizaciones': typeof CotizacionesRoute
  '/nosotros': typeof NosotrosRoute
  '/politicas': typeof PoliticasRoute
  '/tienda/$slug': typeof TiendaSlugRoute
  '/tienda/': typeof TiendaIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/colecciones'
    | '/contacto'
    | '/cotizaciones'
    | '/nosotros'
    | '/politicas'
    | '/tienda/$slug'
    | '/tienda/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/colecciones'
    | '/contacto'
    | '/cotizaciones'
    | '/nosotros'
    | '/politicas'
    | '/tienda/$slug'
    | '/tienda'
  id:
    | '__root__'
    | '/'
    | '/colecciones'
    | '/contacto'
    | '/cotizaciones'
    | '/nosotros'
    | '/politicas'
    | '/tienda/$slug'
    | '/tienda/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ColeccionesRoute: typeof ColeccionesRoute
  ContactoRoute: typeof ContactoRoute
  CotizacionesRoute: typeof CotizacionesRoute
  NosotrosRoute: typeof NosotrosRoute
  PoliticasRoute: typeof PoliticasRoute
  TiendaSlugRoute: typeof TiendaSlugRoute
  TiendaIndexRoute: typeof TiendaIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/politicas': {
      id: '/politicas'
      path: '/politicas'
      fullPath: '/politicas'
      preLoaderRoute: typeof PoliticasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nosotros': {
      id: '/nosotros'
      path: '/nosotros'
      fullPath: '/nosotros'
      preLoaderRoute: typeof NosotrosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cotizaciones': {
      id: '/cotizaciones'
      path: '/cotizaciones'
      fullPath: '/cotizaciones'
      preLoaderRoute: typeof CotizacionesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacto': {
      id: '/contacto'
      path: '/contacto'
      fullPath: '/contacto'
      preLoaderRoute: typeof ContactoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/colecciones': {
      id: '/colecciones'
      path: '/colecciones'
      fullPath: '/colecciones'
      preLoaderRoute: typeof ColeccionesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tienda/': {
      id: '/tienda/'
      path: '/tienda'
      fullPath: '/tienda/'
      preLoaderRoute: typeof TiendaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tienda/$slug': {
      id: '/tienda/$slug'
      path: '/tienda/$slug'
      fullPath: '/tienda/$slug'
      preLoaderRoute: typeof TiendaSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ColeccionesRoute: ColeccionesRoute,
  ContactoRoute: ContactoRoute,
  CotizacionesRoute: CotizacionesRoute,
  NosotrosRoute: NosotrosRoute,
  PoliticasRoute: PoliticasRoute,
  TiendaSlugRoute: TiendaSlugRoute,
  TiendaIndexRoute: TiendaIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
